version: "3.8"
services:

  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    restart: unless-stopped
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - ./vol/cassandra-data:/var/lib/cassandra/data

  thehive:
    image: thehiveproject/thehive4:4.1.9-1
    container_name: thehive
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
      - cortex
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
      - ./vol/data:/opt/data
      - ./vol/index:/opt/index
    command: '--no-config --no-config-secret'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '0.0.0.0:9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./vol/elasticsearch_data:/usr/share/elasticsearch/data
      - ./vol/elasticsearch_logs:/usr/share/elasticsearch/logs

  cortex:
    image: thehiveproject/cortex:3.1.1-1
    container_name: cortex
    restart: unless-stopped
    depends_on:
      - elasticsearch
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf
      - '//var/run/docker.sock:/var/run/docker.sock'
      - '/var/run/cortex/jobs:/tmp/cortex-jobs'
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}    
    ports:
      - '0.0.0.0:9001:9001'

  redis:
    image: redis:6.2.5
    container_name: redis
    restart: unless-stopped

  mysql:
    image: mysql:8.0.30
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=misp"
    volumes:
      - ./vol/mysql:/var/lib/mysql

  misp:
    image: coolacid/misp-docker:core-v2.4.148a
    container_name: misp
    restart: unless-stopped
    depends_on:
      - redis
      - mysql
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    environment:
      - "MYSQL_HOST=mysql"
      - "HOSTNAME=https://localhost"
      - "REDIS_FQDN=redis"
      - TIMEZONE=Europe/Amsterdam
      - "INIT=true"
      - "CRON_USER_ID=1"
      - "DISIPV6=true"

  misp-modules:
    image: coolacid/misp-docker:modules-latest
    container_name: misp-modules
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - mysql

  thephish:
    image: emalderson/thephish:latest
    container_name: thephish
    restart: unless-stopped
    depends_on:
      - thehive
      - cortex
      - misp
    ports:
      - '0.0.0.0:8080:8080'
    volumes:
      - ./thephish_conf_files/analyzers_level_conf.json:/root/thephish/analyzers_level_conf.json
      - ./thephish_conf_files/configuration.json:/root/thephish/configuration.json
      - ./thephish_conf_files/whitelist.json:/root/thephish/whitelist.json